### PR TITLE
repo/riteshharjani: Update branch and other details

### PR DESCRIPTION
**Pull request by riteshharjani**
Update branch and other details.

### CODE REVIEW

**Comment by rli9** [comment]
thanks for the patch

**Comment by riteshharjani** [comment]
@rli9 

Can you please confirm if I also need to provide mail_to fields or whether declaring owner field is enough like in this commit for getting reports? 

Few questions- 
- what exactly is covered as part of "integration_testing_branches"  and "notify_build_success_branch" ? 
- how much time it takes to get the reports? 
- Is it possible to see the status of the build/tests anywhere? 
- Does this only tests build against different configs or boot up and other tests also run?
- any suggestion on below config? 
https://github.com/intel/lkp-tests/pull/385/commits/3a68b7ad329bea895c3d2c31a6b93a99d2eca536

**Comment by rli9** [comment]
> Can you please confirm if I also need to provide mail_to fields or whether declaring owner field is enough like in this commit for getting reports?

I also notice this, thus directly configure this in the commit c5d27007dbf1 ("repo/linux/riteshharjani: configure mail to"). Sorry not to notify you about this.

> what exactly is covered as part of "integration_testing_branches" and "notify_build_success_branch" ?

integration_testing_branches is relatively confusing, as it is only used for finding base for mail patches. We will think of a better name in the future.

notify_build_success_branch is related to build status summary, such as https://lore.kernel.org/lkml/202410291157.sUqPzo6c-lkp@intel.com/

> how much time it takes to get the reports?

for build, it is around 1 day but may be delayed due to resource constrained. For runtime (func and perf), it targets for 1 week to report regression if any and the first bad commit is bisected to be on this repo. BTW: It doesn't mean it is bug free if no report is received, as it is best effort to test and bisect with current resource.

> Is it possible to see the status of the build/tests anywhere?

So far we supply build status summary and build regression report, for which you will receive the email. For runtime testing, we report out regressions, which are archived at https://lore.kernel.org/oe-lkp/.

> Does this only tests build against different configs or boot up and other tests also run?

Yes boot and other runtime testing are executed on IA platforms.

> any suggestion on below config?

No additional suggestions, that it is ok for daily testing.

**Comment by riteshharjani** [comment]
Thanks @rli9 for answering the queries and integrating the mail_to field.

**Pull request merged**
