### PR TITLE
docker: support ubuntu:22.04

### LINKED ISSUE #267: docker: support ubuntu:22.04
### Acceptance Test
* run a few tests (pick 2-3) to confirm rt can be generated successfully

### PR DESCRIPTION
**Pull request by fongjiantan**
Create new Dockerfile in docker/ubuntu/jammy to add support for ubuntu:22.04 image=ubuntu/jammy

Closes #267

### CODE REVIEW

**Comment by rli9** [comment]
Thanks
> because the wrappers have very restrictive kernel version dependency checks
For this one, can you share more detail like what issue is met is the replacement is not done

And can you also show the rt of hackbench and another test case by using this docker?

**Comment by shanscendent** [comment]
Dockerfile
- Changed to installing linux-tools-generic (instead of linux-cpupower) to install perf and turbostat
- However, ubuntu installs wrappers to /usr/bin/turbostat and /usr/bin/perf which has very restrictive kernel checks
- So, added links to the actual binaries that have been installed to replace those wrappers at the end of the RUN command

Adaptation
- Jammy doesn't have libpython3.9, changed to closest available version libpython3.10 instead

Testing
- Tested hackbench, schbench and stress-ng
- hackbench
image
- schbench
image
- stress-ng
image

**Comment by rli9** [comment]
> * However, ubuntu installs wrappers to /usr/bin/turbostat and /usr/bin/perf which has very restrictive kernel checks

Thanks for all the detail, for this one, can you share what issue/failure log if using default turbostat and perf?

**Comment by shanscendent** [comment]
> > * However, ubuntu installs wrappers to /usr/bin/turbostat and /usr/bin/perf which has very restrictive kernel checks
> 
> Thanks for all the detail, for this one, can you share what issue/failure log if using default turbostat and perf?

Definitely.

Here's the output after installing linux-tools-generic
image
I'm showing the beginning part of turbostat as well, you can see it's just a script that checks for kernel versions and requires them to match exactly. Does not make sense to get the user to update the kernel on the host.

Additional reading:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1844201

**Comment by rli9** [comment]
> Does not make sense to get the user to update the kernel on the host.

Got it, thanks a lot for all the detail.

**Pull request merged**
