### PR TITLE
Debian and Ubuntu adaptation fix

### PR DESCRIPTION
**Pull request by Magnani95**
The `distro/adaptation/{debian,ubuntu}` files are updated to avoid installation problem.
**Both:**
- added `bsdtar: libarchive-tools`;

**Ubuntu:**
- add docs-comment at top;
- add `procps-ng: procps`

### CODE REVIEW

**Review by rli9 — COMMENTED** [review]
thanks, is the commit 62c90046d85c72d9194198e49af774288d034955 necessary?

**Comment by Magnani95** [comment]
> thanks, is the commit [62c9004](https://github.com/intel/lkp-tests/commit/62c90046d85c72d9194198e49af774288d034955) necessary? Can do a rebase to base your change on top of current head.

No, sorry! It's a merge I did to have last intel/lkp version in my fork. (Still newbie with git)

**Comment by Magnani95** [comment]
> thanks, is the commit [62c9004](https://github.com/intel/lkp-tests/commit/62c90046d85c72d9194198e49af774288d034955) necessary? Can do a rebase to base your change on top of current head.

No, sorry! It's a merge I did to have last intel/lkp version in my fork. (Still newbie with git)
Do I need to redo the merge request without the [62c9004], or is it something you can easily correct?

**Comment by rli9** [comment]
> Do I need to redo the merge request without the [[62c9004](https://github.com/intel/lkp-tests/commit/62c90046d85c72d9194198e49af774288d034955)], or is it something you can easily correct?
It would be helpful if you can rebase your PR with cleaned commits.

**Pull request closed without merging**
