### PR TITLE
repo: update my current repo and add a new one

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>

### CODE REVIEW

**Review by rli9 — COMMENTED** [review]
Thanks, is it ok to keep this repo name and just update the content of it? We actually have a way to auto deduce the repo name based on url, like git/user/linux.git => user. To keep the origin name is easier for us to detect whether some repos are duplicated (besides the url check).

**Comment by brauner** [comment]
> Thanks, is it ok to keep this repo name and just update the content of it? We actually have a way to auto deduce the repo name based on url, like git/user/linux.git => user. To keep the origin name is easier for us to detect whether some repos are 

Oh sure. Can do that. So that would be:
git/brauner/linux.git -> brauner
git/vfs/idmapping.git -> vfs-idmapping or just vfs?

**Comment by brauner** [comment]
> > Thanks, is it ok to keep this repo name and just update the content of it? We actually have a way to auto deduce the repo name based on url, like git/user/linux.git => user. To keep the origin name is easier for us to detect whether some repos are
> 
> Oh sure. Can do that. So that would be: git/brauner/linux.git -> brauner git/vfs/idmapping.git -> vfs-idmapping or just vfs?

Ok, got it. It needs to be `vfs-idmapping` and it already exists. :) So I fixed things up. Should be fine now!

**Comment by brauner** [comment]
//Cc @sforshee

**Comment by rli9** [comment]
thanks for the patch

**Pull request merged**
