### PR TITLE
repo/linux: add jackchuang

### PR DESCRIPTION
**Pull request by JackChuang**

### CODE REVIEW

**Comment by rli9** [comment]
Thanks, is it possible to name the repo as jackchuang. We have basic naming convention of repo at https://github.com/intel/lkp-tests/wiki/Repo-Naming-Convention, which is not that obvious to be noticed. It is to avoid possible confliction and make it easy to name. For this url, it typically removes linux.git and remains jackchuang.

**Comment by JackChuang** [comment]
Hi @rli9 Done. Please check again. Thank you.

**Comment by rli9** [comment]
thanks for the patch

**Comment by JackChuang** [comment]
Thank you @rli9 for merging it!!

**Pull request merged**
